sonar.projectKey=task-management-tool
sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend
sonar.pullrequest.cache.basepath=C:\\Main\\10p\\Task-Management-Tool

7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.projectKey=task-management-tool:7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364
7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.projectName=TaskManagement.Domain
7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Domain
7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.sourceEncoding=utf-8
7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.sources=\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Domain\\Entities\\AppUser.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Domain\\Entities\\RefreshToken.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Domain\\Entities\\TaskItem.cs"

7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.cs.analyzer.projectOutPaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\0"
7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.cs.roslyn.reportFilePaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\0\\Issues.json"

7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364.sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar\\mod0
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.projectKey=task-management-tool:BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.projectName=TaskManagement.Application
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.sourceEncoding=utf-8
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.sources=\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\AuthResponse.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\CreateTaskRequest.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\LoginRequest.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\RegisterRequest.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\TaskDto.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\TaskSummaryDto.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\DTOs\\UpdateTaskRequest.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\Interfaces\\IAuthService.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Application\\Interfaces\\ITaskService.cs"

BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.cs.analyzer.projectOutPaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\1"
BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.cs.roslyn.reportFilePaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\1\\Issues.json"

BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC.sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar\\mod1
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.projectKey=task-management-tool:ACC3ADFA-8DDD-3565-4823-7DDF45C58008
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.projectName=TaskManagement.Infrastructure
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.sourceEncoding=utf-8
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.sources=\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Data\\AppDbContext.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Migrations\\20260508052650_InitialCreate.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Migrations\\20260508052650_InitialCreate.Designer.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Migrations\\20260606153802_AddTaskItem.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Migrations\\20260606153802_AddTaskItem.Designer.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Migrations\\AppDbContextModelSnapshot.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Services\\AuthService.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Infrastructure\\Services\\TaskService.cs"

ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.cs.analyzer.projectOutPaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\2"
ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.cs.roslyn.reportFilePaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\2\\Issues.json"

ACC3ADFA-8DDD-3565-4823-7DDF45C58008.sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar\\mod2
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.projectKey=task-management-tool:ADBAE72A-9351-A196-7D2D-07EF5E032F9A
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.projectName=TaskManagement.Tests
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Tests
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.sourceEncoding=utf-8
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.sources=
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.tests=\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Tests\\AuthServiceTests.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Tests\\Helpers\\ConfigurationHelper.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Tests\\Helpers\\TestDbContextFactory.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.Tests\\TaskServiceTests.cs"

ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.cs.analyzer.projectOutPaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\3"
ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.cs.roslyn.reportFilePaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\3\\Issues.json"

ADBAE72A-9351-A196-7D2D-07EF5E032F9A.sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar\\mod3
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.projectKey=task-management-tool:1A8020D8-08F3-79F5-3317-1F2D3C46591B
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.projectName=TaskManagement.API
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.projectBaseDir=C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.sourceEncoding=utf-8
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.sources=\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\Controllers\\AuthController.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\Controllers\\TaskController.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\Middleware\\ExceptionMiddleware.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\Program.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.GlobalUsings.g.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.AssemblyInfo.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\obj\\Debug\\net10.0\\TaskManagement.API.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\appsettings.Development.json",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\appsettings.json",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\logs\\log-20260508.txt",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\logs\\log-20260606.txt",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\TaskManagement.API.http",\
"C:\\Main\\10p\\Task-Management-Tool\\backend\\TaskManagement.API\\Properties\\launchSettings.json"

1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.cs.analyzer.projectOutPaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\4"
1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.cs.roslyn.reportFilePaths=\
"C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\4\\Issues.json"

1A8020D8-08F3-79F5-3317-1F2D3C46591B.sonar.working.directory=C:\\Main\\10p\\Task-Management-Tool\\.sonarqube\\out\\.sonar\\mod4
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=7675FA15-ED1F-EE3C-B1D8-E1FBD0C07364,BB8D0B55-15B7-B6FE-2DAC-BB5E4B6532FC,ACC3ADFA-8DDD-3565-4823-7DDF45C58008,ADBAE72A-9351-A196-7D2D-07EF5E032F9A,1A8020D8-08F3-79F5-3317-1F2D3C46591B

